#! /bin/bash

# Dejar al sistema docker que acceda al entorno gráfico
xhost +local:root

# Ejecutar el contenedor comprobando si ha sido creado o no

#variable nombre contenedor
container_name=bellscheduler

#variable nombre imagen
image_name=aosucas499/bellscheduler-dre:bionic

#variable carpeta configuración para compartir con el contenedor
STORAGE_FOLDER=/home/$SUDO_USER/BELLSCHEDULER
CONFIG_FOLDER=~/home/$SUDO_USER/BELLSCHEDULER-config

rm -r $STORAGE_FOLDER

if [ -d "$STORAGE_FOLDER" ]; then
    echo "Carpeta $STORAGE_FOLDER existe"
else
    echo "Creando carpeta $STORAGE_FOLDER"
    mkdir $STORAGE_FOLDER
    chown -R $SUDO_USER:$SUDO_USER $STORAGE_FOLDER
fi


#if [ -d "$CONFIG_FOLDER" ]; then
#    echo "Carpeta $CONFIG_FOLDER existe"
#else
#    echo "Creando carpeta $CONFIG_FOLDER"
#    mkdir $CONFIG_FOLDER
#fi

docker stop $container_name && docker rm $container_name 

# Lanzamos el contenedor creándolo si no existe.

sleep 5
if docker ps -a --format '{{.Names}}' | grep -Eq "^${container_name}\$"; then
   	docker start ${container_name}

else



docker run -t -i --rm --privileged \
 --net=host -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v /dev:/dev \
 --volume="/run/dbus/system_bus_socket:/run/dbus/system_bus_socket" \
 -e DISPLAY="$DISPLAY" \
 -v $XSOCK:$XSOCK:rw \
    -v $XAUTH:$XAUTH:rw \
    -e XAUTHORITY=$XAUTH \
 -v /home/admin/file_example_MP3_5MG.mp3:/root/file_example_MP3_5MG.mp3 \
 --workdir=/root \
 --volume="/etc/group:/etc/group:ro" \
 --volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" \
 --name ${container_name} ${image_name} 

fi

#-v /home/admin/.config/pulse/cookie:/home/usuario/.config/pulse/cookie \
# --group-add $(getent group audio | cut -d: -f3) \
#-e PULSE_SERVER=unix:{$XDG_RUNTIME_DIR}/pulse/native \
# -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native:Z \
 #--volume=/run/user/1001:/run/user/1001/pulse \
 #-v /etc/pulse:/etc/pulse \
 # -v /home/admin:/home/admin \
 #--user=$(id -u $SUDO_USER):$(id -g $SUDO_USER) \
 # -e NO_AT_BRIDGE=1 \
 # --volume="/run/dbus/system_bus_socket:/run/dbus/system_bus_socket" \
