#! /bin/bash

# Borrado de archivos anteriores de bellscheduler-dre
#
echo ""
echo -e "${ROJO}Borrando antiguos archivos de bellscheduler-dre${NORMAL}"
echo ""
echo -e "${ROJO}Deleting old files from bellscheduler-dre${NORMAL}"
echo ""
sleep 3
##
#
sudo rm /etc/xdg/autostart/bellscheduler-dre.desktop

sudo rm /usr/share/applications/bellscheduler-dre.desktop

sudo rm /usr/bin/bellscheduler-dre

sudo rm /etc/sudoers.d/zz-bellscheduler-dre

sudo docker stop bellscheduler

sudo docker rm bellscheduler

sudo docker rmi aosucas499/bellscheduler-dre

sudo docker rmi aosucas499/bellscheduler-dre:bionic

sudo docker rmi aosucas499/bellscheduler-dre:xenial

sudo docker rmi aosucas499/bellscheduler-dre:focal

#sudo delgroup docker

#sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y

sudo mv /etc/cron.d/localBellScheduler /home/$USER/localBellScheduler.backup

echo ""
echo -e "${ROJO}Copia de seguridad de las alarmas ${NORMAL}"
echo ""
echo -e "${ROJO}en la carpeta de tu usuario${NORMAL}"
echo ""
echo -e "${ROJO}Si necesita restaurarla copie el archivo${NORMAL}"
echo ""
echo -e "${ROJO}en la carpeta /etc/cron.d${NORMAL}"
sleep 3

