#! /bin/bash

# Borrado de archivos anteriores de bellscheduler-dre
#
echo ""
echo -e "${ROJO}Borrando antiguos archivos de bellscheduler-dre${NORMAL}"
echo ""
echo -e "${ROJO}Deleting old files from bellscheduler-dre${NORMAL}"
echo ""
sleep 3
##
#
sudo rm /etc/xdg/autostart/bellscheduler-dre.desktop

sudo rm /usr/share/applications/bellscheduler-dre.desktop

sudo rm /usr/bin/bellscheduler-dre

sudo rm /etc/sudoers.d/zz-bellscheduler-dre

sudo rm -r /usr/lib/python3/dist-packages/bellscheduler-dre-appindicator

sudo rm /etc/xdg/autostart/bellscheduler-dre-appindicator.desktop

sudo rm -r /home/$SUDO_USER/BELLSCHEDULER

sudo mv /etc/cron.d/localBellScheduler

sudo docker stop bellscheduler

sudo docker rm bellscheduler

sudo docker rmi aosucas499/bellscheduler-dre

sudo docker rmi aosucas499/bellscheduler-dre:bionic

sudo docker rmi aosucas499/bellscheduler-dre:xenial

sudo docker rmi aosucas499/bellscheduler-dre:focal

#sudo delgroup docker

#sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y



